### ISSUE TITLE
Called setState() on an unmounted component.

### ISSUE THREAD

**Issue by HyperMaxime** [danieltimpone/react-background-image-loader#2]
Hi,

I was trying your component and kept facing this error when changing app routes:

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the BackgroundImage component.

I ended up solving it by unreferencing the onload and onerror functions on the image object:

```
componentWillUnmount() {
    this.image.onload = null;
    this.image.onerror = null;
    this.image = null;
}
```

I hope this helps others facing similar issues.

Regards,
Maxime

**Comment by danieltimpone** [comment]
Thanks for suggesting this fix, it's been taken care of in #4
