### ISSUE TITLE
why 'img' ? It's 'src' instead

### ISSUE THREAD

**Issue by pimkle** [danieltimpone/react-background-image-loader#3]
Hello, below is my code:

`
<BackgroundImage className={"img-carousel"} placeholder={this.state.placeholder} src={'http://imgtest.xxx.com/20170309232350329448'}>
</BackgroundImage>
`

when I repace 'src' with 'img', image always fail to load, why document told us to use 'img'  ?

It is not until I read the source code did I found out, kinda waste of time.

**Comment by danieltimpone** [comment]
Sorry, that slipped through the cracks some how. Thanks for pointing it out, it's been resolved.
